#!/usr/bin/env python3
"""
Build a signed-out-proof preview of the member portal.

The portal pages talk to Supabase, so they cannot be opened or screenshotted
without a real login. This generates site/_harness/, a throwaway copy of the
portal pages wired to fixtures instead, so the layout can be looked at and
iterated on offline. Fixtures are chosen with ?state=paid|unpaid|board.

    python3 tools/harness.py && cd site && python3 -m http.server 8899
    open http://localhost:8899/_harness/account.html?state=paid

It regenerates from the real pages every run, so it cannot drift. Nothing here
is served in production: site/_harness/ is git-ignored.
"""
import os, re, shutil, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "site")
OUT = os.path.join(SITE, "_harness")
PAGES = ["account.html"]

FIXTURES = r"""
const STATE = new URLSearchParams(location.search).get("state") || "paid";

const PROFILES = {
  paid:   { id:"u1", full_name:"Riad Jawhar", email:"member@example.org", phone:"76 123 456",
            student_id:"BAU-2201", university:"Beirut Arab University", academic_year:"4th year", role:"member" },
  unpaid: { id:"u2", full_name:"Lea Haddad", email:"lea@example.org", phone:"",
            student_id:"", university:"Lebanese University", academic_year:"2nd year", role:"member" },
  board:  { id:"u3", full_name:"Omar Nasr", email:"treasurer@example.org", phone:"71 998 244",
            student_id:"USJ-1904", university:"Universite Saint-Joseph", academic_year:"5th year", role:"super_admin" },
};

const MEMBERSHIPS = {
  paid:   [{ academic_year:"2026-2027", status:"paid",    method:"whish", created_at:"2026-09-14T10:00:00Z", verified_at:"2026-09-15T08:30:00Z" },
           { academic_year:"2025-2026", status:"paid",    method:"Cash",  created_at:"2025-09-20T10:00:00Z", verified_at:"2025-09-22T09:00:00Z" }],
  unpaid: [],
  board:  [{ academic_year:"2026-2027", status:"pending", method:"whish", created_at:"2026-09-14T10:00:00Z", verified_at:null }],
};

const COUNTS = { paid:[4,2,1], unpaid:[0,0,0], board:[7,3,5] };

window.__FIXTURE = {
  session: { user: { id: PROFILES[STATE].id, email: PROFILES[STATE].email } },
  profile: PROFILES[STATE],
  memberships: MEMBERSHIPS[STATE],
};

/* A stand-in for the supabase-js client. It answers the handful of chains the
   portal pages actually use and resolves to canned counts. */
const counts = COUNTS[STATE];
let served = 0;
function thenable(result) {
  const chain = new Proxy(function () {}, {
    get(_, prop) {
      if (prop === "then") return (res) => res(result);
      return () => chain;
    },
    apply() { return chain; },
  });
  return chain;
}
window.supabase = {
  createClient() {
    return {
      auth: {
        getSession: async () => ({ data: { session: window.__FIXTURE.session } }),
        signOut:    async () => ({ error: null }),
        updateUser: async () => ({ error: null }),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe(){} } } }),
      },
      from() { return thenable({ data: [], error: null, count: counts[served++ % counts.length] }); },
      storage: { from: () => thenable({ data: { path: "x" }, error: null }) },
    };
  },
};
"""

STUB = """/* Generated by tools/harness.py. Do not edit. */
import * as real from "../js/portal.js";

export const { sb, signOut, signIn, signUp, getSession, requestPasswordReset,
  updatePassword, resendConfirmation, passwordProblem, authMessage, ROLE_LABEL,
  isAdmin, isStaff, isCommitteeHead, currentAcademicYear, duesYear, DUES_LABEL,
  isPaidUp, fmtDate, escapeHtml, say, submitPayment, proofUrl, METHODS,
  SUPABASE_URL, SUPABASE_KEY } = real;

export async function requireAuth()   { return window.__FIXTURE.session; }
export async function getProfile()    { return window.__FIXTURE.profile; }
/* The fixture's newest row is stamped with whatever duesYear() says today, so
   the "paid" state stays paid as the academic year rolls over. */
export async function getMemberships(){
  const rows = window.__FIXTURE.memberships;
  return rows.length ? [{ ...rows[0], academic_year: real.duesYear() }, ...rows.slice(1)] : rows;
}
"""


def build():
    shutil.rmtree(OUT, ignore_errors=True)
    os.makedirs(OUT)
    open(os.path.join(OUT, "portal-stub.js"), "w", encoding="utf-8").write(STUB)

    for page in PAGES:
        html = open(os.path.join(SITE, page), encoding="utf-8").read()
        # the real client never loads here; the fixture script installs a stand-in
        html = html.replace('<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>',
                            "<script>\n" + FIXTURES + "\n</script>")
        html = html.replace('from "./js/portal.js"', 'from "./portal-stub.js"')
        html = re.sub(r'(href|src)="(css|assets|js)/', r'\1="../\2/', html)
        html = html.replace('href="/favicon.ico"', 'href="../favicon.ico"')
        html = html.replace('<meta charset="UTF-8">',
                            '<meta charset="UTF-8">\n<!-- PREVIEW HARNESS. Generated file, not served in production. -->')
        open(os.path.join(OUT, page), "w", encoding="utf-8").write(html)
        print(f"  {page}")

    print(f"Built {len(PAGES)} page(s) into site/_harness/. "
          f"Try ?state=paid, ?state=unpaid, ?state=board")


if __name__ == "__main__":
    build()
